"""Generate crates/core/src/vocab.rs from the installed usaddress package.

Reads DIRECTIONS and STREET_NAMES from usaddress so the Rust sets are
mechanically identical to the oracle's, not hand-transcribed.
"""

from pathlib import Path

import usaddress

OUT = Path(__file__).parent.parent / "crates" / "core" / "src" / "vocab.rs"


def rust_set(name, values):
    items = "\n".join(f'    "{v}",' for v in sorted(values))
    return f"pub static {name}: &[&str] = &[\n{items}\n];\n"


def main():
    src = (
        "// GENERATED by tools/gen_vocab.py from usaddress "
        "(see model/PROVENANCE.md for version). Do not edit by hand.\n\n"
        + rust_set("DIRECTIONS", usaddress.DIRECTIONS)
        + "\n"
        + rust_set("STREET_NAMES", usaddress.STREET_NAMES)
    )
    OUT.write_text(src, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}: {len(usaddress.DIRECTIONS)} directions, {len(usaddress.STREET_NAMES)} street names")


if __name__ == "__main__":
    main()
